openapi: 3.0.0
info:
  title: Weather API Service
  description:
    A weather API service that searches for weather based on zip code
  version: 0.0.1
servers: 
  - url: 'http://localhost:8080'
    description: Local dev server

paths:
  /temp/{zipcode}:
    get:
      summary: Retrieves the entry for the temperature with the give ID.
      parameters:
        - name: temp
          in: path
          required: true
          description: ID of the temperature you would like to retrieve.
          schema:
            type: integer
            format: int64
            minimum: 1
      responses:
    '200':
          description: weather for given ZIP Code.
          content: JSON Object
          application/json:
              schema:
                $ref: '#/components/schemas/temp'
  /conditions/{zipcode}:
    description: Local dev server
    get:
      summary: weather for given ZIP Code.
      parameters:
        - name: conditions
          in: path
          required: true
          description: ZIP code.
          schema:
            type: integer
            format: int64
            minimum: 1
      requestBody: None
      required: true
      content:
          application/json:
            schema:
              $ref: '#/components/schemas/conditions'
    responses:
        '200':
          description: Zip Code successfully updated.
        '422':
          description: Zip Code Number is out of bounds.
components:
  schemas:
    Weather:
      properties:
        Conditions
          type: String
        Temperature
          type: int
        fahrenheit
          type: int
        celsius
          type: int
        wind speed
          type: int
        wind direction
          type: int
        skies 
          type: String
        precipitation
          type: String