openapi: 3.0.0
info:
  title: Game Store REST Service
  description:
    A simple database backed REST inventory management web service for a Video Game Store
  version: 0.0.1
servers:
  - url: 'http://localhost:8080'
    description: Local dev server
    
paths:
  /game:
    post:
      summary: Creates a new game
      description: Adds a new game object to the database
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/GamePost'
      responses:
        '201':
          description: Created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GameResponse'
        '422':
          description: Unprocessable Entity
          content:
            application/json:
              schema:
                type: string
        
    get:
      summary: Get all games
      description: Searches database for list of all games
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GameResponse'

  /game/{game_id}:
    get:
      summary: Get game by id
      description: Searches database for game by id
      parameters: 
        - name: id
          in: path
          required: true
          description: Game id
          schema:
            type: string
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GameResponse'
        '422':
          description: Unprocessable Entity
          content:
            application/json:
              schema:
                type: string
        '404':
          description: Not found
          content:
            application/json:
              schema:
                type: string
                
    put:
      summary: Update game by id
      description: Updates game by id  
      parameters:
        - name: id
          in: path
          required: true
          description: Game id
          schema:
            type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/GameUpdate'
      responses:
        '204':
          description: No Content
        '422':
          description: Unprocessable Entity
          content:
            application/json:
              schema:
                type: string
        '404':
          description: Not found
          content:
            application/json:
              schema:
                type: string
                
    delete:
      summary: Deletes game by id
      description: Deletes game by id 
      parameters:
        - name: id
          in: path
          required: true
          description: Game id
          schema:
            type: string
      responses:
        '204':
          description: No Content
        '404':
          description: Not found
          content:
            application/json:
              schema:
                type: string
        '422':
          description: Unprocessable entity
          content: 
            application/json:
              schema:
                type: string
                  
  /game/studio/{studio}:
    get:
      summary: Get games by studio
      description: Searches database for list of games by studio
      parameters: 
        - name: studio
          in: path
          required: true
          description: name of game studio
          schema:
            type: string
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GameResponse'

  /game/esrb/{esrb_rating}:
    get:
      summary: Get games by ESRB rating
      description: Searches database for list of games with given ESRB rating
      parameters: 
        - name: esrb_rating
          in: path
          required: true
          description: ESRB rating of game
          schema:
            type: string
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GameResponse'

  /game/title/{title}:
    get:
      summary: Get games by title
      description: Searches Database for list of games by title
      parameters: 
        - name: title
          in: path
          required: true
          description: game title
          schema:
            type: string
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GameResponse'

  /console:
    post:
      summary: Creates a new console
      description: Adds a new console object to the database
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ConsolePost'
      responses:
        '201':
          description: Created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ConsoleResponse'
        '422':
          description: Unprocessable Entity
          content:
            application/json:
              schema:
                type: string
          
    get:
      summary: Get all consoles
      description: Searches database for list of all consoles
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GameResponse'

  /console/{console_id}:
    get:
      summary: Get console by id
      description: Searches database for console by id
      parameters: 
        - name: id
          in: path
          required: true
          description: Console id
          schema:
            type: string
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ConsoleResponse'
        '422':
          description: Unprocessable Entity
          content:
            application/json:
              schema:
                type: string
                
    put:
      summary: Updates console by id
      description: Updates console by id 
      parameters:
        - name: id
          in: path
          required: true
          description: Console id
          schema:
            type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ConsoleUpdate'
      responses:
        '204':
          description: No Content
        '422':
          description: Unprocessable Entity
          content:
            application/json:
              schema:
                type: string
        '404':
          description: Not found
          content:
            application/json:
              schema:
                type: string
                
    delete:
      summary: Deletes console by id
      description: Deletes console by id in path
      parameters:
        - name: id
          in: path
          required: true
          description: Console id
          schema:
            type: string
      responses:
        '200':
          description: No Content
        '404':
          description: Not found
          content:
            application/json:
              schema:
                type: string
        '422':
          description: Unprocessable entity
          content:
            application/json:
              schema:
                type: string
                
  /console/manufacturer/{manufacturer}:
    get:
      summary: Gets consoles by manufacturer
      description: Searches database for list of consoles by manufacturer
      parameters: 
        - name: manufacturer
          in: path
          required: true
          description: console manufacturer
          schema:
            type: string
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ConsoleResponse'
      
  /tshirt:
    post:
      summary: Creates a new t-shirt
      description: Adds a new t-shirt object to the database
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TshirtPost'
      responses:
        '201':
          description: Created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TshirtResponse'
        '422':
          description: Unprocessable Entity
          content:
            application/json:
              schema:
                type: string
          
    get:
      summary: Gets all t-shirts
      description: Searches database for list of all t-shirts
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GameResponse'
      
  /tshirt/{t_shirt_id}:
    get:
      summary: Get t-shirt by id
      description: Searches database for t-shirt by id
      parameters: 
        - name: id
          in: path
          required: true
          description: T-shirt id
          schema:
            type: string
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TshirtResponse'
        '422':
          description: Unprocessable Entity
          content:
            application/json:
              schema:
                type: string
                
    put:
      summary: Updates t-shirt by id
      description: Updates t-shirt by id 
      parameters:
        - name: id
          in: path
          required: true
          description: T-shirt id
          schema:
            type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TshirtUpdate'
      responses:
        '204':
          description: No Content
        '422':
          description: Unprocessable Entity
          content:
            application/json:
              schema:
                type: string
        '404':
          description: Not found
          content:
            application/json:
              schema:
                type: string
    delete:
      summary: Deletes t-shirt by id
      description: Deletes t-shirt by id in path
      parameters:
        - name: id
          in: path
          required: true
          description: Tshirt id
          schema:
            type: string
      responses:
        '204': 
          description: No Content
        '422':
          description: Unprocessable Entity
          content:
            application/json:
              schema:
                type: string
        '404':
          description: Not found
          content:
            application/json:
              schema:
                type: string
                  
  /tshirt/color/{color}:
    get:
      summary: Get t-shirts by color
      description: Searches database for list of t-shirts by color
      parameters: 
        - name: color
          in: path
          required: true
          description: t-shirt color
          schema:
            type: string
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TshirtResponse'
                
  /tshirt/size/{size}:
    get:
      summary: Gets tshirts by size
      description: Searches database for list of tshirts by size
      parameters: 
        - name: size
          in: path
          required: true
          description: tshirt size
          schema:
            type: string
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TshirtResponse'
                
  /purchase:
    post:
      summary: Creates a new purchase
      description: Adds an invoice object to DB
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PurchasePost'
      responses:
        '201':
          description: Created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InvoiceResponse'
        '404':
          description: Not found
          content:
            application/json:
              schema:
                type: string
        '422':
          description: Unprocessable Entity
          content:
            application/json:
              schema:
                type: string
                
  /invoice:
    get:
      summary: Gets all invoices
      description: Searches database for list of all invoices
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InvoiceResponse'
                
  /invoice/{invoice_id}:
    get:
      summary: Gets invoice by id
      description: Searches database for invoice by id
      parameters: 
        - name: id
          in: path
          required: true
          description: InvoiceDao id
          schema:
            type: string
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InvoiceResponse'
        '422':
          description: Unprocessable Entity
          content:
            application/json:
              schema:
                type: string
          
components:
  schemas:
    PurchasePost:
      type: object
      properties:
        name:
          type: string
        street:
          type: string
        city:
          type: string
        state:
          type: string
        zipcode:
          type: string
        item_type:
          type: string
        item_id:
          type: number
        quantity:
          type: number
      required:
        - name
        - street
        - city
        - state
        - zipcode
        - item_type
        - item_id
        - quantity
        
    InvoiceResponse:
      type: object
      properties:
        id:
          type: number
        name:
          type: string
        street:
          type: string
        city: 
          type: string
        state:
          type: string
        zipcode:
          type: string
        item_type:
          type: string
        item_id:
          type: number
        unit_price:
          type: number
        quantity:
          type: number
        subtotal:
          type: number
        tax:
          type: number
        processing_fee:
          type: number
        total:
          type: number

    GamePost:
      type: object
      properties:
        title:
          type: string
        esrb_rating:
          type: string
        description:
          type: string
        price:
          type: number
        studio:
          type: string
        quantity:
          type: number
      required: 
        - title
        - esrb_rating
        - description
        - price
        - studio
        - quantity
    
    GameUpdate:
      type: object
      properties:
        title:
          type: string
        esrb_rating:
          type: string
        description:
          type: string
        price:
          type: number
        studio:
          type: string
        quantity:
          type: number
    
    GameResponse:
      type: object
      properties:
        id:
          type: number
        title:
          type: string
        esrb_rating:
          type: string
        description:
          type: string
        price:
          type: number
        studio:
          type: string
        quantity:
          type: number
          
    ConsolePost:
      type: object
      properties:
        model:
          type: string
        manufacturer:
          type: string
        memory_amount:
          type: string
        processor:
          type: string
        price:
          type: number
        quantity:
          type: number
      required: 
        - model
        - manufacturer
        - memory_amount
        - processor
        - price
        - quantity
    
    ConsoleUpdate:
      type: object
      properties:
        model:
          type: string
        manufacturer:
          type: string
        memory_amount:
          type: string
        processor:
          type: string
        price:
          type: number
        quantity:
          type: number
    
    ConsoleResponse:
      type: object
      properties:
        id:
          type: number
        model:
          type: string
        manufacturer:
          type: string
        memory_amount:
          type: string
        processor:
          type: string
        price:
          type: number
        quantity:
          type: number

    TshirtPost:
      type: object
      properties:
        size:
          type: string
        color:
          type: string
        description:
          type: string
        price:
          type: number
        quantity:
          type: number
      required: 
        - size
        - color
        - description
        - price
        - quantity
    
    TshirtUpdate:
      type: object
      properties:
        size:
          type: string
        color:
          type: string
        description:
          type: string
        price:
          type: number
        quantity:
          type: number
    
    TshirtResponse:
      type: object
      properties:
        id:
          type: number
        size:
          type: string
        color:
          type: string
        description:
          type: string
        price:
          type: number
        quantity:
          type: number
        
            
            